### ISSUE TITLE
MetaStudent, MetaStudent.backup 

### ISSUE THREAD

**Issue by anapetrovska** [Rostlab/MetaStudent#1]
@jmcejuela 

Can you please explain to me what is happening with this repos and which one should be our working repository? I pushed on MetaStudent, but I realized that MetaStudent.backup is also existing. 

Thanks!

**Comment by juanmirocks** [comment]
Yes, use the `MetaStudent`. I just created the backup just in case.

@anapetrovska If you don't need the backup anymore, please tell me so and I will delete the repo.

**Comment by anapetrovska** [comment]
@jmcejuela the backup is not needed, you can delete it.

Thanks!
