### ISSUE TITLE
Data not installed by default via apt

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/MetaStudent#10]
``` shell
metastudent -i test.fasta -o /tmp/fuckyou.result
Error: DATABASE_3_BASE_PATH (/usr/share/metastudent-data-3/dataset_201401) does not exist
```

Furthermore, the requested file is metastudent-data-3 ?? (not 1 nor 2)

**Comment by anapetrovska** [comment]
@jmcejuela metastudent-data-3 doesn't exist.

**Comment by juanmirocks** [comment]
The `metastudentrc` file has the property `DATABASE_3_BASE_PATH=<default-data-package-3-path>/dataset_201401` -- it seem to agree with the folder structure of `metastudent-data`

**Comment by juanmirocks** [comment]
Please also document this as part of #12
