### ISSUE TITLE
Which blast needed ?

### ISSUE THREAD

**Issue by anshkapil** [Rostlab/MetaStudent#2]
@jmcejuela The program creates blast pgp commands.
Which blast version needs to be installed for this.
I tried with ncbi-blast-2.2.31+ , but the program is generating an exception in that case.

**Comment by lrrichter** [comment]
Please have a look at http://nebc.nox.ac.uk/bioinformatics/docs/blastpgp.html
It looks like you tried the new BLAST+ package but blastpgp is part of the old one

**Comment by juanmirocks** [comment]
@anshkapil is this working now?

**Comment by anshkapil** [comment]
@jmcejuela Hi 

I tried to run it with blast-2.2.26 but it throws some error during the running of the blast query.

I debugged it using eclipse and found that the query is created properly but while running the blast, there is still some problem.

I also checked that the blastpgp executable was present in the path.

Should I contact the author for this problem ? or I can also meet you if you have some idea to solve this problem.

Regards,
Ansh

**Comment by juanmirocks** [comment]
Thank you Ansh,

I'm gonna study this today or latest tomorrow.

For the moment, please make sure the develop README contains all the
necessary info for installation and running. As far as you can get it
running.

I send you more info soon.

**Comment by anshkapil** [comment]
@jmcejuela 

yes, we have developed the readme, and you will find the instructions there. Possible there is a problem with configuring of blastpgp, which we will update as soon as possible. I have also contacted Mr. Hamp for his feedback regarding this.

Thanks for your support.

Regards,
Ansh

**Comment by juanmirocks** [comment]
Thanks @anshkapil 

I don't know what could be the problem. I don't mind the blast version as long as it's working. Did Tobias provide info on this, or is it otherwise solved already?

Don't hesitate to make an appointment and come to my office if needed.

**Comment by anshkapil** [comment]
This blast version was found
