### ISSUE TITLE
New repository "MetaStudent-data" needed

### ISSUE THREAD

**Issue by anapetrovska** [Rostlab/MetaStudent#3]
- [x] Commit data via git-lfs
- [x] Why point to dropbox data when is already on github

---

@jmcejuela please create a new repo where we can push .git conversion from "svn+ssh://rostlab.org/mnt/project/subversion/metastudent/metastudent-data"

Thanks!

**Comment by juanmirocks** [comment]
Thanks. I contact our administrator to do this

**Comment by juanmirocks** [comment]
The repos (-data & -data2) should now be accessible.

Report otherwise.

Thank you.

**Comment by anapetrovska** [comment]
@jmcejuela 

We can't find github repos -data and -data2. We cannot push the data without it. 

The tool can't be run without the data being present as explained in the read me. 

Please provide it, because we all can't test the tool. After the data repositories are created, we need to update the readme also explaining the data cloning for the tool to run.

Thanks!

**Comment by juanmirocks** [comment]
You mean that you got access to the svn repos, but you need me to create the github repos for the data?

Another thing to consider would be to actually decide to host those files not in a in version control system but in a static place (dropbox or github large files). Please serve those files somehow for now so that I can take a look and decide

**Comment by anapetrovska** [comment]
@jmcejuela Probably a misunderstanding happened.

I will upload the data on dropbox and share the link with you. Also if needed I can come or someone else from the team, to discuss further about the data, but as I said only if needed.

Thank you very much for everything until now.

**Comment by juanmirocks** [comment]
Yes please, upload the data and pate here the link so that it's easier for
me to check.

LIkely, if it's just data, we don't need to create code repos for them.
Let's see.

**Comment by juanmirocks** [comment]
*Paste

**Comment by anapetrovska** [comment]
@jmcejuela 

Please find attached the Dropbox link where you can find the data. 

https://www.dropbox.com/sh/3hm0w3jom6hwr46/AABIATIewd_byccHGUK89tQxa?dl=0

**Comment by juanmirocks** [comment]
It would be better to commit this data via for example git-lfs so that we make sure the files don't disappear over time.

**Comment by anapetrovska** [comment]
@jmcejuela 

Sorry for the long silence. I will commit the data.

**Comment by juanmirocks** [comment]
:+1: thanks

**Comment by anapetrovska** [comment]
The data is committed with Git Large File Storage.

**Comment by juanmirocks** [comment]
Thanks. I just reopen to check tomorrow.

**Comment by anshkapil** [comment]
Updated the readme for that.

**Comment by juanmirocks** [comment]
:+1:
