### ISSUE TITLE
Provide HOWTO install from source

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/MetaStudent#5]
See https://github.com/Rostlab/MetaStudent/issues/4#issuecomment-173618366

**Comment by anshkapil** [comment]
@jmcejuela I contacted Tobias Hamp regarding this, to which he mailed me this: 

"
 I suggest you first follow the default installation procedure of metastudent and then go from there. You can install metastudent on any Debian-based system with "sudo apt-get install metastudent". Also keep in mind that metastudent depends on a series of other packages, including metastudent-data packages. The latter have to be ported to git as well. Also for building metastudent (this is necessary for it to work), you will probably need to change the debian package files, as it assumes SVN repositories. I have never ported a Debian package to git, so I cannot help you with this, sorry.
"

This is the reason we updated our readme steps accordingly.

If possible can we meet on Tuesday in your office and discuss more about this ?

Regards
Ansh

**Comment by anshkapil** [comment]
Hi,

Mr. Tobias Hamp replied to the email we sent, and he told that the new version is unstable and is under testing. He also gave the link to the debian package.

https://packages.debian.org/search?keywords=metastudent

Should we still attempt to run this from source, or just use this package and update the details about this version ?

**Comment by juanmirocks** [comment]
I see. Fine, document appropriately all the different versions and that will be enough for now.
