### ISSUE TITLE
Package not available

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/MetaStudent#7]
On a default Vagrant debian/wheezy64 machine, I get that the package `metastudent` doesn't exist. Do we need to add the rostlab repo or do we need a newer debian version?

Please clarify on README

**Comment by anshkapil** [comment]
Did you install Metastudent via apt-get ?

**Comment by juanmirocks** [comment]
Yes. -- Regarding the meeting, we can do it tomorrow from 10am to 5pm. Please send me a calendar invitation

**Comment by anshkapil** [comment]
Invitation sent for 2.2.2015 at 16:00 at juanmi@jmcejuela.com

**Comment by juanmirocks** [comment]
Wait 11:30 or 16?

**Comment by anshkapil** [comment]
I sent an invitation for 16:00 .. Can you confirm me the suitable final time ??

**Comment by juanmirocks** [comment]
I actually received an invitation for 11:30. I don't mind the time, but
please review and resend your calendar invitation.

**Comment by anshkapil** [comment]
I guess due to default setting of my email client, the invitation sent was in Indian time zone... Sorry for the confusion

**Comment by juanmirocks** [comment]
Fine. Meet you at my office, today, at 16:00
